#!/usr/bin/env php
<?php

require_once(__DIR__.'/vendor/autoload.php');
EvilGlobals::init('config.neon');
CommandLineOptions::cron_job();
EvilGlobals::setup();

$report = new PullRequestReport();
$report->run();
