#!/usr/bin/env php
<?php

require_once(__DIR__.'/vendor/autoload.php');

use GetOptionKit\OptionCollection;
use BoostTasks\Settings;
use BoostTasks\CommandLineOptions;
use BoostTasks\GitHubEvents;
use BoostTasks\SuperProject;
use BoostTasks\LocalMirror;
use BoostTasks\UpdateExplicitFailures;

function main($args) {
    $specs = new OptionCollection;
    $options = CommandLineOptions::process($args,
        'Update explicit failure markup in the super project',
        $specs);
    if (is_numeric($options)) { exit($options); }
    Settings::init($options);

    // Update the mirror
    GitHubEvents::downloadEvents();
    $mirror = new LocalMirror();
    $mirror->refresh();
    $mirror->fetchDirty();

    // Update explicit-failures-markup
    foreach (Settings::branchRepos() as $x) {
        UpdateExplicitFailures::update(new SuperProject($x));
    }
}

main($_SERVER['argv']);