#!/usr/bin/env php
<?php

require_once(__DIR__.'/vendor/autoload.php');

use BoostTasks\TempDirectory;
use BoostTasks\BinTrayCache;
use BoostTasks\Documentation;

function main() {
    $options = CommandLineOptions::process($_SERVER['argv'],
        'Update the website development documentation from BinTray.');
    if (is_numeric($options)) { exit($options); }
    EvilGlobals::init($options);

    foreach(array('master', 'develop') as $branch) {
        try {
            Documentation::install($branch, $branch);
        }
        catch(RuntimeException $e) {
            Log::error($e);
        }
    }
}

main();
