#!/usr/bin/env php
<?php

require_once(__DIR__.'/vendor/autoload.php');

use GetOptionKit\OptionCollection;
use BoostTasks\Settings;
use BoostTasks\CommandLineOptions;
use BoostTasks\PullRequestReport;

function main($args) {
    $specs = new OptionCollection;
    $options = CommandLineOptions::process($_SERVER['argv'],
        'Update the pull request report from GitHub.', $specs);
    if (is_numeric($options)) { exit($options); }
    Settings::init($options);

    PullRequestReport::update();
}

main($_SERVER['argv']);
