#!/usr/bin/env php
<?php

require_once(__DIR__.'/vendor/autoload.php');
EvilGlobals::init('config.neon');
$options = CommandLineOptions::process($_SERVER['argv'],
    'Update the pull request report from GitHub.');
EvilGlobals::setup();

$report = new PullRequestReport();
$report->run();
