#!/bin/bash -e

# Exit on error
set -e
# Treat unset parameters as an error
set -u

cwd=$(pwd)
cd $(dirname $0)
root=$(pwd)
cd -
. $root/settings.sh

upload_documentation()
{
    upload_cowic || echo "Upload to cowic failed."

    if [ -f $root/upload/upload-master ]; then
        upload_to_server master || echo "Upload master docs failed."
    fi

    if [ -f $root/upload/upload-develop ]; then
        upload_to_server develop || echo "Upload develop docs failed."
    fi
}

upload_to_server()
{
    branch=$1
    boost_root=$(cat $root/upload/upload-$branch)

    if [ -d ${boost_root} ]
    then
        if rsync -az --delete-after \
            ${boost_root}/ \
            dnljms@boost.org:/home/www/shared/archives/live/$branch/
        then
            echo "Uploaded $branch to boost server"
            rm $root/upload/upload-$branch
        else
            echo "Failed to upload $branch to boost server"
        fi
    fi
}

upload_cowic()
{
    nl="
"
    cd $root/upload

    for f in $(ls *.upload)
    do
        f2=$(echo $f | sed "s/\.upload$//")
        echo "Uploading $f2"

        echo "put $f ${nl} rename $f $f2" | ftp -v boost.cowic.de 2>&1 | tee upload.log

        if grep '^250 Rename successful' upload.log
        then
            rm $f
        fi

        rm upload.log
    done
}

upload_documentation $*
