#!/usr/bin/env php
<?php

/* 
 * Copyright 2013 Daniel James <daniel@calamity.org.uk>.
 *
 * Distributed under the Boost Software License, Version 1.0. (See accompanying
 * file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
 */

require_once(__DIR__.'/vendor/autoload.php');

try {
    $dst = EvilGlobals::$data_root.'/upload';

    if (is_dir($dst)) {
        Process::run("rm -r {$dst}");
    }

    mkdir($dst);

    Process::run("git archive master | tar -x -C {$dst}", __DIR__);
    Process::run("git rev-parse HEAD > {$dst}/commit_hash.txt", __DIR__);

    #Process::run("rm -r {$dst}/nbproject");
    Process::run("rm {$dst}/upload-this-to-server");
    Process::run("rsync -az {$dst}/ dnljms@boost.org:boost-tasks/");

    // Tag the upload.
    $tags = array();
    foreach(Process::read_lines('git tag', __DIR__) as $tag) {
        $tags[$tag] = true;
    }
    for($count = 1;true;++$count) {
        $tag = "upload-".date('Ymd')."-{$count}";
        if (!array_key_exists($tag, $tags)) {
            Process::run("git tag {$tag}", __DIR__);
            break;
        }
    }
}
catch (\RuntimeException $e) {
    Log::error("Runtime exception: {$e}");
    exit(1);
}

// Return an error code if an error was logged.
if (Log::$error) {
    exit(1);
}
